title: Fan Shi # your name (or website title) here
logo: "/images/2寸照.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of Urban spatial analysis, University of Pennsylvania 
  <br><br>
  Bachelor of Geographical State Monitoring, Wuhan University
  <br><br>
  <a href="https://www.linkedin.com/in/%E9%92%92-%E7%9F%B3-bb9318198/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-100000-0 # your Google Analytics tracking ID here
